### ISSUE TITLE
Reading initial brightness from DDC/CI-compatible display

### ISSUE THREAD

**Issue by dastefster** [fnesveda/ExternalDisplayBrightness#10] opened 2019-12-15 01:21 UTC
I’m having an issue with the app reading the initial brightness from my external display. I have the ‘read initial brightness from display’ option checked in the app’s preferences & **my display does support DDC/CI**. However, the initial brightness is still set to 50% when changing the it for the first time.

I’m not sure if this is a compatibility problem is or a bug in the app, but I’ve included some info about my set up below hoping you might be able to tell me?

**System Info**:
- Early 2015 MBP running macOS 10.15.2
- ExternalDisplayBrightness v1.3.0
- External display: benQ GW2265HM

thanks in advance!

**Comment by fnesveda** [comment] 2019-12-15 08:59
Hi,

thanks for the report!

I'm afraid it's a compatibility issue with the monitor itself, a lot of them don't support reading values over DDC/CI, just writing them. None of the monitors I have (from Samsung, AOC and NEC) actually supports reading the brightness either, I think it's pretty rare for a monitor to support it (I've heard from a few users that it works for them, though, so I think the code in the app is actually right).

If you want to confirm this, perhaps you could try using [ddcctl](https://www.github.com/kfix/ddcctl) to try and read the current brightness from the display, and see if it works? If it does, that means the problem is with my app, and I'll try to fix it, if it doesn't, the monitor is probably incompatible and there's not much I can do.

Thanks!

**Comment by dastefster** [comment] 2020-01-01 06:13
yeah.. I was kinda figuring that was the case, but I wanted to ask. it's not big deal anyway, I'm just glad I dont have to fumble with the monitor controls to change the brightness anymore haha

thanks for the info!

**Comment by dastefster** [comment] 2020-01-01 06:20
> I'm afraid it's a compatibility issue with the monitor itself, a lot of them don't support reading values over DDC/CI, just writing them. None of the monitors I have (from Samsung, AOC and NEC) actually supports reading the brightness either, I think it's pretty rare for a monitor to support it (I've heard from a few users that it works for them, though, so I think the code in the app is actually right). 

yeah.. I was kinda figuring that was the case, but I wanted to ask.

> If you want to confirm this, perhaps you could try using ddcctl

ok, I might give that try just to see. it's not big deal either way, I'm just glad I dont have to fumble with the monitor controls to change the brightness anymore haha

thanks for the info!

**Comment by fnesveda** [comment] 2020-01-02 07:55
No problem! I'm going to close the issue for now, since it's (most probably) not caused by ExternalDisplayBrightness, so it unfortunately can't be solved here.

**Closed as completed by fnesveda** 2020-01-02 07:55 UTC
